// <auto-generated />
namespace DCNE_Cake.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductDateCreatedField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductDateCreatedField));
        
        string IMigrationMetadata.Id
        {
            get { return "201606261024040_ProductDateCreatedField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
