// <auto-generated />
namespace DCNE_Cake.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserAndProduct1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAndProduct1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041614090_UserAndProduct1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
